image: goodforgod/debian-jdk10-oracle

stages:
  - build
  - notify

cache:
  paths:
    - .gradle/caches
    - .gradle/wrapper

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
      paths:
        - build/libs/*.jar