image: goodforgod/debian-jdk10-oracle

stages:
  - build

cache:
  paths:
    - .gradle/caches
    - .gradle/wrapper

before_script:
  - apt-get install -y git

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
      paths:
        - build/libs/*.jar